### ISSUE TITLE
The implement of Resnet12 backbone

### ISSUE THREAD

**Issue by sunhm15** [baiksung/L2F#1]
Hi, thank you for your implement L2F in pytorch.

But I found the implement is based on the conv4 backbone，could you release the implement of Resnet12 backbone?

**Comment by baiksung** [comment]
Hi,

Thank you for your interest in our paper.
We are currently working on the code optimization of training with ResNet12 backbone.
I believe this will be finished soon.

If you are in a rush, you can follow the description in the paper or TADAM code (https://github.com/ElementAI/TADAM/blob/master/model/tadam.py) caveat: the TADAM code is in tensorflow.

**Comment by baiksung** [comment]
Hi,

Sorry for the delay.
We have just updated the code with the support for ResNet12.
Hope it helps! :)
